# Numpy

1. Numy is a libary used for Scientific computing and important part is numpy array and from that array we make matrix, maxed array and etc.

2. Can apply Statistical and mathematical omn the given data.

3. Python was slow processing libraries becasue of it developmnet as in data we sue GB data. Numpy was build in C but it can be used on python as it was easy and quick to understand as no of people from differnt domain were expected to join Data Science Java and C were compliacted.

4. Pandas, Matplotlib, Scikit in background uses Numpy array.

5. Numpy Arrays Vs Python Sequences 
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.. 

## Creating Numpy Arrays

In [6]:
# np. array
# 1D array is vector
import numpy as np

a= np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [8]:
# 2D and 3D
# 2D/3D is matrix
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c= np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [13]:
#dtype

a1= np.array([1,2,3],dtype=float)
a2= np.array([1,2,3],dtype=bool)
a3= np.array([1,2,3],dtype=complex)

print(a1)
print(a2) #all true because 1 is true 2 is true and 3 is also true as per the machine
print(a3)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [17]:
#np.arange
a3= np.arange(1,11)

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
#reshape

a3.shape

(10,)

In [21]:
a3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
a3.reshape(2,5)   #product of he number need to be equal to no of array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
#np.ones and np.zero

np.ones((3,4))  #used to initialize weight in the neural network

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.random.random((3,4))

array([[0.88004908, 0.53860241, 0.28560759, 0.03741791],
       [0.43304449, 0.94674111, 0.00252421, 0.13583074],
       [0.16374138, 0.53653846, 0.92828913, 0.25438434]])

In [31]:
#np.linspace Linear space
# on equal distance creat point between the two points
np.linspace(-10,10,10) #lower, Upper, no. in the range

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [32]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ## Array Attributes

In [34]:
a1= np.arange(10)  #1D
a2= np.arange(12,dtype=float).reshape(3,4)  #MAtrix
a3= np.arange(8).reshape(2,2,2)  #Tensore 3D

In [36]:
#ndim to know no of dimensions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [37]:
#shape to know the shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [38]:
#size no of items

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [39]:
#itemsize no of space capture no. of bytes
print(a1.itemsize)    #int32 takes 4bytes and int64 takes 8 bytes
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [40]:
print(a1.dtype)  
print(a2.dtype)
print(a3.dtype)

int32
float64
int32
